const StyleDictionary = require('style-dictionary').default;

/**
 * 把 W3C DTCG tokens 生成 Kotlin/Compose 常量。
 *
 * 顶层分组约定（与 docs/plan-docs/ui-layer-design.md §3.2 序列表对应）：
 *   color   -> AppColors   （Color(0xFF…)）
 *   spacing -> AppSpacing  （n.dp）
 *   radius  -> AppRadius   （n.dp）
 *   elevation-> AppElevation（n.dp）
 *   sizing  -> AppSizing   （n.dp）
 *   layout  -> AppLayout   （n.dp）
 *   motion  -> AppMotion   （n）——时长（ms）
 */
StyleDictionary.registerFormat({
  name: 'kotlin/tokens',
  format: ({ dictionary }) => {
    const groups = {};
    for (const t of dictionary.allTokens) {
      const cat = t.path[0];
      (groups[cat] = groups[cat] || []).push(t);
    }

    /** 路径段转 Camel：['brand','primary']->BrandPrimary（含中间段，避免跨组重名） */
    const kotlinName = (path) =>
      path.slice(1).map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');

    const emitObject = (cat, members) => {
      const entries = members
        .map((t) => {
          if (t.path.length < 2) return '';
          const name = kotlinName(t.path);
          const rawVal = (t.original && t.original.$value != null) ? t.original.$value : t.value;
          const raw = t.original || t;
          const desc = raw && raw.$description ? ` // ${raw.$description}` : '';
          if (cat === 'color') {
            const c = String(rawVal || '').replace('#', '0xFF');
            return `    val ${name} = Color(${c})${desc}`;
          }
          if (cat === 'motion') {
            return `    val ${name} = ${String(rawVal)}L // ${String(rawVal)}ms${desc}`;
          }
          return `    val ${name} = ${String(rawVal)}.dp${desc}`;
        })
        .filter((s) => s)
        .join('\n');
      if (!entries) return '';
      const className = `App${cat.charAt(0).toUpperCase()}${cat.slice(1)}`;
      return `object ${className} {\n${entries}\n}`;
    };

    const objects = [];
    for (const [cat, tokens] of Object.entries(groups)) {
      const obj = emitObject(cat, tokens);
      if (obj) objects.push(obj);
    }

    const sb = [];
    sb.push('@file:Suppress("ObjectPropertyName")');
    sb.push('');
    sb.push('// @generated by Style Dictionary from newui/tokens/*.tokens.json — 禁止手改');
    sb.push('package com.core.deepcode.newui.designsystem.token.generated');
    sb.push('');
    sb.push('import androidx.compose.ui.graphics.Color');
    sb.push('import androidx.compose.ui.unit.dp');
    sb.push('');
    sb.push(objects.join('\n\n'));
    sb.push('');
    return sb.join('\n');
  },
});

module.exports = {
  source: ['tokens/**/*.tokens.json', 'tokens/**/*.json'],
  platforms: {
    android: {
      // 不套 transformGroup；产物直接落到 src/main（单一 committed 副本，IDE 可直接 import）
      buildPath: 'src/main/java/com/core/deepcode/newui/designsystem/token/generated/',
      files: [
        {
          destination: 'AppTokens.kt',
          format: 'kotlin/tokens',
        },
      ],
    },
  },
};